### ISSUE TITLE
我遇到了一个关于appbarlayout verticalOffset 的问题

### ISSUE THREAD

**Issue by tianshaokai** [CTSN/TestCollapsingToolbarLayout#1]
1. 我的页面 SwipeRefreshLayout CollapsingToolbarLayout 嵌套刷新，滑动冲突
2.  appBarLayout.addOnOffsetChangedListener(new AppBarLayout.OnOffsetChangedListener() {
            @Override
            public void onOffsetChanged(AppBarLayout appBarLayout, int verticalOffset) {
                Logger.getLogger().d("verticalOffset: " + verticalOffset);
                if (verticalOffset >= 0) {
                    swipeRefreshLayout.setEnabled(true);
                } else {
                    swipeRefreshLayout.setEnabled(false);
                }
            }
        });

设置了监听后，发现页面并没有滚动到顶部就可以下拉刷新了，导致页面上拉后 无法正常下拉

**Comment by CTSN** [comment]
你应该 这样判断
public void onOffsetChanged(AppBarLayout appBarLayout, int verticalOffset) {
Logger.getLogger().d("verticalOffset: " + verticalOffset);
swipeRefreshLayout.setEnabled(verticalOffset==0);
}
});

为0 就是appbaylayout 滑动到原来位置，就可以下拉刷新了

**Comment by CTSN** [comment]
你应该 这样判断
public void onOffsetChanged(AppBarLayout appBarLayout, int verticalOffset) {
Logger.getLogger().d("verticalOffset: " + verticalOffset);
swipeRefreshLayout.setEnabled(verticalOffset==0);
}
});

为0 就是appbaylayout 滑动到原来位置，就可以下拉刷新了
你试下这样

**Comment by tianshaokai** [comment]
我现在写了== 0 ，也会出现 无法 下拉问题，（页面还没有滑动到顶部就出现了 下拉刷新控件）

这个问题并不是一直存在 ，就是偶尔出现

**Comment by CTSN** [comment]
会不会是你布局的问题 ，我这边ptr下拉刷新+CoordinatorLayout嵌套 也是这样解决的，没出现你说的问题

**Comment by tianshaokai** [comment]
@CTSN  能不能加你qq或微信 交流一下

**Comment by CTSN** [comment]
我发个demo 你看下吧 我用的是ptr下拉刷新 https://github.com/SNCTTOO/TestScrollStatusBar

**Comment by tianshaokai** [comment]
逻辑几乎差不多，我现在就是偶尔下拉刷新会遇到，就简单的测试一下并不会碰到该问题，
1. 我的布局里使用了这个属性 android:fitsSystemWindows="true"
2. 在列表的外层包了一个相对布局 加了一个这个属性：app:behavior_overlapTop="170dp"
会不会是这两个属性 导致的问题呢？

**Comment by CTSN** [comment]
android:fitsSystemWindows="true" 这个属性会影响verticalOffset。好像会加上状态栏高度这个值

**Comment by CTSN** [comment]
qq：519405585

**Comment by tianshaokai** [comment]
我搜索文章试试
