### ISSUE TITLE
双手滑动----左手向上滑动appbarlayout，同时右手向下滑动NestedScrollView时，双手同时操作，出现界面抖动

### ISSUE THREAD

**Issue by Asmewill** [CTSN/TestCollapsingToolbarLayout#2]

**Comment by Asmewill** [comment]
![image](https://user-images.githubusercontent.com/16815386/45858182-b84f2380-bd8e-11e8-9348-af7fbf3796af.png)

**Comment by Asmewill** [comment]
package com.m520it.myapplication;

import android.content.Context;
import android.support.design.widget.AppBarLayout;
import android.support.design.widget.CoordinatorLayout;
import android.support.v4.view.ViewCompat;
import android.util.AttributeSet;
import android.view.MotionEvent;
import android.view.View;
import android.widget.OverScroller;

import java.lang.reflect.Field;

/**
 * Created by jian.shui on 2018/7/9.
 */

public class CustomBehavior extends AppBarLayout.Behavior{
    private OverScroller mScrollers;
    public CustomBehavior() {
    }

    public CustomBehavior(Context context, AttributeSet attrs) {
        super(context, attrs);
        getParentScroller(context);
    }

    /**
     * 反射获得滑动属性。
     *
     * @param context
     */
    private void getParentScroller(Context context) {
        if (mScrollers != null) return;
        mScrollers = new OverScroller(context);
        try {
            Class<?> reflex_class = getClass().getSuperclass().getSuperclass();//父类AppBarLayout.Behavior  父类的父类   HeaderBehavior
            Field fieldScroller = reflex_class.getDeclaredField("mScroller");
            fieldScroller.setAccessible(true);
            fieldScroller.set(this, mScrollers);
        } catch (Exception e) {}
    }
    //fling上滑appbar然后迅速fling下滑recycler时, HeaderBehavior的mScroller并未停止, 会导致上下来回晃动
    @Override
    public void onNestedPreScroll(CoordinatorLayout coordinatorLayout, AppBarLayout child, View target, int dx, int dy, int[] consumed, int type) {
        if(mScrollers!=null){ //当recyclerView 做好滑动准备的时候 直接干掉Appbar的滑动
            if (mScrollers.computeScrollOffset()) {
                mScrollers.abortAnimation();
            }
        }
        if (type == ViewCompat.TYPE_NON_TOUCH&&getTopAndBottomOffset() == 0) { //recyclerview 鸡儿的 惯性比较大 会顶在头部一会儿  到头直接干掉它的滑动
            ViewCompat.stopNestedScroll(target, type);
        }

        super.onNestedPreScroll(coordinatorLayout, child, target, dx, dy, consumed, type);
    }

    @Override
    public boolean onTouchEvent(CoordinatorLayout parent, AppBarLayout child, MotionEvent e) {

        switch (e.getActionMasked()) {
            case MotionEvent.ACTION_DOWN:
                break;
        }
        return super.onTouchEvent(parent,child,e);
    }

}

**Comment by Asmewill** [comment]
看我截图，给appbarlayout添加layout_behavior属性，同时去掉layout_scrollFlag中的sanp属性即可，解决抖动问题

**Comment by CTSN** [comment]
@Asmewill 谢谢指教，代码是好久之前拿来练手用的。
